[package]
name = "musicalcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# essentials
tokio = { version = "1.35.1", features = [
    "rt",
    "rt-multi-thread",
    "fs",
    "sync",
    "parking_lot",
] }
poise = { git = "https://github.com/serenity-rs/poise/" }
songbird = { version = "0.4.0", features = ["builtin-queue"] }

# errors/loggings
log = "0.4.20"
simplelog = "0.12.1"
eyre = "0.6.11"
reqwest = "0.11.23"

# parsings
toml = "0.8.8"
serde = "1.0.193"
regex = "1.10.2"
humantime = "2.1.0"

# shuffle
rand = "0.8.5"
