[package]
name = "musicalcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# essentials
tokio = { version = "1.28.2", features = ["rt", "rt-multi-thread", "fs", "sync", "parking_lot"] }
poise = "0.5.5"
songbird = { version = "0.3.2", features = ["builtin-queue", "yt-dlp"] }

# errors/loggings
log = "0.4.18"
simplelog = "0.12.1"
eyre = "0.6.8"
simple-eyre = "0.3.1"

# parsings
toml = "0.7.4"
serde = "1.0.163"
regex = "1.8.3"
humantime = "2.1.0"

# shuffle
rand = "0.8.5"
