[package]
name = "musicalcat"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# essentials
tokio = { version = "1.36.0", features = [
    "rt",
    "rt-multi-thread",
    "fs",
    "sync",
    "parking_lot",
] }
poise = "0.6.1"
#{ git = "https://github.com/serenity-rs/poise/" }
songbird = { version = "0.4.0", features = ["builtin-queue"] }
reqwest = { version = "0.11.24", default-features = false, features = [
    "rustls-tls",
] }

# errors/loggings
log = "0.4.20"
simplelog = "0.12.1"
eyre = "0.6.12"

# parsings
toml = "0.8.10"
serde = "1.0.196"
regex = "1.10.3"
humantime = "2.1.0"

# shuffle
rand = "0.8.5"
